### ISSUE TITLE
New function 

### ISSUE THREAD

**Issue by shado-hackers** [Samfun75/BookdlBot#13]
Can you add please userid  who use bot. Like this 
[@OMG_info #eBOOKbot] 
User Id: 1238794447
Engineering Mechanics Dynamics (Solutions Manual).pdf
![IMG_20221024_092720](https://user-images.githubusercontent.com/70184956/197446052-c8ca36c6-12a8-41a2-b0c8-813e39b821ad.jpg)
![IMG_20221024_092449](https://user-images.githubusercontent.com/70184956/197446056-a53d98ca-46ae-4160-a607-4287515a39ed.jpg)

**Comment by shado-hackers** [comment]
![IMG_20221024_093010](https://user-images.githubusercontent.com/70184956/197446319-11a8fe88-bd62-4047-91a3-501f4eb5ea9a.jpg)

**Comment by Samfun75** [comment]
Tracking users activity without the need for the bot's functionalities is unnecessary and also tracking without their consent is unethical.
