### ISSUE TITLE
How to fill the Database variables?

### ISSUE THREAD

**Issue by shado-hackers** [Samfun75/BookdlBot#8]
db_host = 
db_username = 
db_password = 
db_name = 
db_type = 

I can't understand

     res = uri_parser.parse_uri(
2021-11-02T11:24:29.439955+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pymongo/uri_parser.py", line 461, in parse_uri
2021-11-02T11:24:29.439956+00:00 app[worker.1]:     raise InvalidURI('Bad database name "%s"' % dbase)
2021-11-02T11:24:29.439956+00:00 app[worker.1]: pymongo.errors.InvalidURI: Bad database name "/LUSIFER:LUSIFER@cluster0"
2021-11-02T11:24:48.364311+00:00 app[api]: Scaled to worker@0:Free by user 
2021-11-02T11:24:48.475995+00:00 heroku[worker.1]: State changed from up to down
2021-11-02T11:24:49.205208+00:00 heroku[worker.1]: Stopping all processes with SIGTERM
2021-11-02T11:24:49.286000+00:00 app[worker.1]: 2021-11-02 11:24:49,285 - root - INFO - Stop signal received (15). Exiting...
2021-11-02T11:24:49.715916+00:00 heroku[worker.1]: Process exited with status 0
 Autoscroll with outputSave
Blogs
Careers
Documentati

**Comment by Samfun75** [comment]
```db_host = xxxxxxxxxx.xxxxx.mongodb.net or localhost```
This is the address of the machine where the MongoDB is running
```db_username = username```
Username of your mongodb user. if you host your own mongo community, you must enable authentication for your db
```db_password = password```
Password of your mongodb user. if you host your own mongo community, you must enable authentication for your db
```db_name = BookdlBot```
The database name, could be anything really
```db_type = Mongo_Atlas or Mongo_Community```
This is used to decide whether **+srv** is added to the uri cause mongo atlas always needs it and mongo community hosted by yourself doesn't unless specified.

As an example you get a mongodb URI you get from mongo atlas that look like this:
mongodb+srv://**_db_username_**:**_db_password_**@**_db_host_**/**_db_name_**?retryWrites=true&w=majority

**Comment by shado-hackers** [comment]
![Screenshot_2021-11-03-13-46-08-284_com android chrome](https://user-images.githubusercontent.com/70184956/140029463-dda4aa9d-1957-484c-9f7c-2ae2615e7462.jpg)


What is the problem. **** please fix this****

**Comment by Samfun75** [comment]
If you are using Heroku make sure you environment variables are correctly set. did you deploy with the Deploy button or Heroku cli?

If you can, hide the sensitive information and send a screenshot of your environment variables concerning the database?

**Comment by shado-hackers** [comment]
![Screenshot_2021-11-03-17-20-02-751_com android chrome](https://user-images.githubusercontent.com/70184956/140055032-c04a5343-6877-430c-8d8a-df149478ea88.jpg)
Look
![Screenshot_2021-11-03-17-19-57-348_com android chrome](https://user-images.githubusercontent.com/70184956/140055045-13460504-1036-4af8-865d-e1b6065a357f.jpg)
**I deploy via deploy botton**

**Comment by Samfun75** [comment]
The var where there is "mongodb+s..." is wrong. idk which key you put that in but refer to my first comment and correct it.
if that is db_host, from your mongo URI copy the text after @ till /

Note: the full URI I provided as example _(mongodb+srv://db_username:db_password@db_host/db_name?retryWrites=true&w=majority)_ is for reference purpose and should not be inserted in any of the vars.

**Comment by shado-hackers** [comment]
Can you please check  what is wrong [check](https://nekobin.com/nuvuceruju)

**Comment by Samfun75** [comment]
mongodb+srv://BookdlBot:BookdlBot@cluster0.xyoj4.mongodb.net/BookdlBot?retryWrites=true&w=majority

For the above URI this is how you put the info to the variables

db_host = cluster0.xyoj4.mongodb.net
db_username = BookdlBot
db_password = BookdlBot
db_name = BookdlBot
db_type = Mongo_Atlas

**And I hope you change the Username and Password!!!**

BTW I forgotten to mention if you haven't allow access to your cluster from any network you should do so [Resource](https://docs.atlas.mongodb.com/security/ip-access-list/#add-ip-access-list-entries). since that is out side of the bots scope we won't be discussing it here
